### ISSUE TITLE
Add code coverage testing

### ISSUE THREAD

**Issue by nmate980829** [BME-MIT-IET/iet-hf2021-iet-meg-nem-latott-a-vilag#6]
# Add [Instanbul] (https://istanbul.js.org/)
Checking code coverage is vital to any widely tested project to ensure the functionality and stability of the code. [Instanbul] (https://istanbul.js.org/) is a code coverage library for js which integrates well with MochaJs.

**Comment by naddam** [comment]
#11 included it.

**Comment by adamkaposi** [comment]
More coverage testing can be added.
